version: 2

references:

  prepare_docker: &prepare_docker
    setup_remote_docker:
      docker_layer_caching: true
      version: 18.06.0-ce

  dependencies_key: &dependencies_key
                      sbt-v2-deps-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - *dependencies_key
        - sbt-v2-deps-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
        - sbt-v2-deps-{{ checksum "project/build.properties" }}
        - sbt-v2-deps

  sbt_image: &sbt_image
    moia/scala-on-circleci:8u222-2.12.10-sbt-1.3.3

  sbtCommand: &sbtCommand
    docker:
      - image: *sbt_image
    steps:
      - checkout
      - *prepare_docker
      - *restore_dependencies
      - run:
          name: Run sbt command
          command: |
            sbt -J-Xms512m -J-Xmx2g -J-XX:+UseConcMarkSweepGC -J-XX:ReservedCodeCacheSize=256m -J-XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -no-colors -batch "$SBT_COMMAND"
      - save_cache:
          key: *dependencies_key
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
      - store_artifacts:
          path: target/license-reports/
          destination: license-reports

jobs:

  test:
    <<: *sbtCommand
    environment:
      SBT_COMMAND: "test"

  scapegoat:
    <<: *sbtCommand
    environment:
      SBT_COMMAND: "scapegoat"

workflows:
  version: 2

  # This test workflow is executed for all PRs
  testDevelopmentBranch:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
            tags:
              ignore: /.*/